### ISSUE TITLE
Collaborative reproductions

### ISSUE THREAD

**Issue by abogdanoski** [BITSS/SSRP_Feedback#2]
### Use case
Allow users to invite others as collaborators, after which all users will be listed as the authors of the reproduction.

### Description of the problem and the proposed solution
As of August 2021, reproductions can only be initiated and submitted by just one user. Allowing contributions from more than one user per single reproduction will make it possible for users to take on more complex papers.

### Link to examples and research
N/A

### Can you develop or write the feature?
The SSRP team will develop this feature soon!

**Comment by clarabicalho** [comment]
Any updates on the timeline for this feature @abogdanoski? Or suggestions for how to best credit all collaborators in the meantime?

**Comment by abogdanoski** [comment]
Hey @clarabicalho, thanks for bringing this up! I think we're at least 2 months away from rolling out this feature. If you need to submit your work sooner than that, I recommend adding the names of your collaborators (specifying how you'd like to credit them) in the free form comments box when submitting the reproduction (see the exact question circled in the attached screenshot). We can then work on including their names as formal collaborators in the metadata once the collaborative reproductions feature rolls out. Would that work?
![image](https://user-images.githubusercontent.com/43018042/161869040-50ae51e8-9bf5-4fbb-94ba-7502c0063c96.png)

**Comment by AphraChen** [comment]
> ## Collaborative Reproductions
> ### Use case
> Allow users to invite others as collaborators, after which all users will be listed as the authors of the reproduction.
> 
> ### Description of the problem and the proposed solution
> As of August 2021, reproductions can only be initiated and submitted by just one user. Allowing contributions from more than one user per single reproduction will make it possible for users to take on more complex papers.
> 
> ### Link to examples and research
> N/A
> 
> ### Can you develop or write the feature?
> The SSRP team will develop this feature soon!

Hi! My name is Zejun Chen. Our group just submitted our reproduction efforts for the paper "Mining and Local Corruption." I'm so sorry that I forgot to add their names in the comments box. Would you please include their names as formal collaborators? Their names are Jane Angar and Charlotte Zell. Would you also please delete this message after fixing the problem for privacy concerns? Sorry about the inconvenience that I might bring. @abogdanoski 

Very best,
Zejun Chen

**Comment by fhoces** [comment]
Hi Zejun, 
Thank you for your interest in doing a collaborative reproduction in the SSRP. We plant to deploy the collaborative feature by the end of the Summer. Once its out we can add your collaborators to your reproduction retroactively. 
Best, 
Fernando
