### ISSUE TITLE
Unable to Access Forum

### ISSUE THREAD

**Issue by chuyishang** [BITSS/SSRP_Feedback#6]
## Expected Behavior

I expected that when I click "Forum" it would lead me to the forum.
## Current Behavior

When I try to click to the forum, regardless of whether I click from the link or from the button, it leads me to the Account Confirmation page (it always redirects me to this link https://forum.socialsciencereproduction.org/u/account-created). However, I have already confirmed multiple times (I am logged in as well), but it still does not let me access the forum.
## Possible Solution

Not sure.
## Steps to Reproduce

![Screen Shot 2022-03-02 at 1 25 08 PM](https://user-images.githubusercontent.com/86524294/156464776-9ed0e2ac-6ace-4086-bfe2-1a2207349fda.png)
<img width="1390" alt="Screen Shot 2022-03-02 at 3 06 49 PM" src="https://user-images.githubusercontent.com/86524294/156464822-6e6d150a-1699-4a64-a8b1-7c539f0f7d4b.png">

**Comment by abogdanoski** [comment]
Hi @chuyishang, I see that you're in the Forum now. Did you figure out what was wrong?
Thanks,
Aleks
