### ISSUE TITLE
Wording Change to Avoid Confusion

### ISSUE THREAD

**Issue by chuyishang** [BITSS/SSRP_Feedback#7]
When filling in __Availability of Materials__ and __Computation__ in __Step 5: Assess Display Items__, all of the boxes in these 2 fields are greyed out and data is not able to be inputted if the previous section __Required Materials__ is not fully completed. However, instead of saying `"You haven't responded to the previous section yet, please do so before filling out this section"`, it instead says that `"You may skip this section because the Diagram Builder did not contain a reproduction tree for this display item."`. This can be a source of confusion, so changing the error message would probably help make the issue more clear. 
## Expected Behavior

There should be a message saying you should complete the previous parts if applicable.
## Current Behavior

It says that the source of error is that the figure isn't in the tree instead.
## Possible Solution

Changing the display text to: `"You haven't responded to the previous section yet, please do so before filling out this section"` could help avoid confusion.
Moreover, even when it says `"You may skip this section..."`, it could allow users to still input data anyways.
## Steps to Reproduce

<img width="1388" alt="Screen Shot 2022-03-02 at 4 47 35 PM" src="https://user-images.githubusercontent.com/86524294/156474536-bbe7fa1d-27b7-48bf-b0c3-b7689fc5dc87.png">

**Comment by abogdanoski** [comment]
Thanks for this helpful suggestion @chuyishang! The "availability of materials" section is only accessible if you'd recorded a reproducibility diagram/tree, which itself isn't required, hence that section can be skipped if you also skipped creating a reproduction tree. Does that make sense?

**Comment by fhoces** [comment]
The issue has a point. A reproducer might just be navigating forward in the assessment section (see screenshot below) and may have not finished the "required materials" subsection. Let's modify the message in bold to: 
"Please make sure you have completed the Required Materials section, before moving forward. If you have completed it, you may skip this section because the Diagram Builder did not contain a reproduction tree for this display item."

**Comment by fhoces** [comment]
I submitted the new copy in this PR #f0ebb72

**Comment by abogdanoski** [comment]
Here's an updated copyedit: 
"Please make sure you have completed the "Required Materials" section before moving forward.
If you have completed it indicating that the Diagram Builder did not contain a reproduction tree for this display item, then you can skip this section".

**Comment by fhoces** [comment]
Added in this PR <https://github.com/BITSS/ACRE_website/pull/501#issue-1177137296>
